name: quickcheck-demo
version: "0.1"
license: "BSD3"
author: "Sönke Hahn"
copyright: "Zalora South East Asia Pte Ltd"
maintainer: "shahn@gmail.com"

tests:
  spec:
    main: "Spec.hs"
    ghc-options: "-threaded -O0"
    source-dirs:
      - src
      - test

    dependencies:
      - hspec
      - QuickCheck
